async (page) => {
 const checks = [];
 const assert = (value, label) => { if (!value) throw Error(label); checks.push(label); };
 await page.goto('http://127.0.0.1:8767/');
 await page.evaluate(() => {sessionStorage.clear(); localStorage.setItem('drsk-language','en');});
 await page.reload();
 await page.locator('#pipelineState.live').waitFor({timeout:30000});
 await page.locator('[data-demo="collab"]').click();
 await page.waitForFunction(() => document.querySelector('#intentPanel').classList.contains('visible') || document.querySelector('#forceNiyet'));
 if (await page.locator('#forceNiyet').count()) await page.locator('#forceNiyet').click();
 await page.locator('#intentPanel.visible').waitFor();
 await page.locator('[data-intent="collaborate"]').click();
 await page.locator('#routeIntent').click();
 await page.waitForFunction(() => !document.querySelector('#acceptMatch').disabled);
 const before = await page.locator('#matchType').innerText();
 await page.locator('#skipMatch').click();
 await page.waitForFunction(previous => document.querySelector('#matchType').textContent !== previous, before);
 assert(true, 'Skip reallocates or explicitly leaves request unmatched');
 await page.locator('#composerText').fill('I am looking for a teammate who knows FastAPI for a weekend prototype. Who wants to collaborate?');
 await page.locator('#forceNiyet').waitFor();
 await page.locator('#forceNiyet').click();
 assert(await page.locator('#intentPanel').isVisible(), 'False negative can be corrected manually');
 await page.locator('[data-intent="discuss"]').click();
 await page.locator('#dismissIntent').click();
 assert(!(await page.locator('#intentPanel').isVisible()), 'Author can dismiss routing');
 await page.locator('[data-demo="evidence"]').click();
 await page.locator('#evidenceCard:not([hidden])').waitFor();
 await page.locator('#composerText').fill('Short');
 await page.locator('#publishPost').click();
 assert(await page.locator('.demo-user-post').first().locator('.post-evidence-disclosure').count() === 0, 'New text never inherits evidence for an older post');
 await page.locator('#composerText').fill('I think this movie is terrible.');
 await page.waitForFunction(() => document.querySelector('#evidenceStatus').textContent.includes('No factual claim'));
 await page.locator('#evidenceToggle').click();
 assert(await page.locator('#askPerson').isHidden(), 'Opinion does not invite factual verification escalation');
 await page.setViewportSize({width:390,height:844});
 await page.locator('#mobileInboxButton').click();
 await page.keyboard.press('Shift+Tab');
 assert(await page.evaluate(() => document.querySelector('.right-rail').contains(document.activeElement)), 'Mobile drawer traps reverse keyboard navigation');
 await page.keyboard.press('Escape');
 assert(await page.locator('#mobileInboxButton').evaluate(el => el===document.activeElement), 'Mobile drawer returns focus to trigger');
 await page.locator('#openTechnical').click();
 assert(await page.locator('#productExperience').evaluate(el => el.inert), 'Modal background is inert');
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:1440,height:1000});
 await page.evaluate(() => document.documentElement.style.fontSize='200%');
 assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '200% text resizing avoids horizontal page overflow');
 await page.evaluate(() => document.documentElement.style.fontSize='');
 await page.evaluate(() => window.confirm = () => false);
 await page.locator('#resetDemo').click();
 assert(await page.locator('.demo-user-post').count() > 0, 'Cancelled reset preserves local posts');
 await page.evaluate(() => window.confirm = () => true);
 await page.locator('#resetDemo').click();
 await page.waitForFunction(() => !document.querySelector('.demo-user-post'));
 assert(true, 'Confirmed reset clears session');
 await page.route('**/api', route => route.fulfill({status:503,contentType:'application/json',body:'{}'}));
 await page.reload();
 await page.locator('#pipelineState.fallback').waitFor();
 await page.locator('[data-demo="help"]').click();
 await page.locator('#intentPanel.visible').waitFor();
 await page.locator('#routeIntent').click();
 await page.locator('#routeResult.visible').waitFor();
 assert(await page.locator('#acceptMatch').isDisabled(), 'Offline mode never fabricates an eligible responder');
 await page.unroute('**/api');
 await page.goto('http://127.0.0.1:8767/not-a-route');
 assert(await page.locator('h1').innerText()==='Page not found', 'Unknown route provides recovery navigation');
 await page.goto('http://127.0.0.1:8767/');
 return {passed:checks.length,checks};
}
